---
title: "List of publications"
---


1.	GBD 2017 HIV collaborators, Global, regional, and national incidence, prevalence, and mortality of HIV, 1980–2017, and forecasts to 2030, for 195 countries and territories: a systematic analysis for the Global Burden of Diseases, Injuries, and Risk Factors Study 2017, the Lancet HIV, August 2019, https://doi.org/10.1016/S2352-3018(19)30196-1. 
2.	Tesfaye B;  Atique S; Azim A; Kebede M, Predicting Skilled delivery service use in Ethiopia: dual application of logistic regression and machine learning BMC Medical Informatics and Decision Making, 19(209), DOI: https://doi.org/10.1186/s12911-019-0942-5.
3.	Kebede M.M., Schuett C,  Pischke C.R., The Role of Continuous Glucose Monitoring, Diabetes Smartphone Applications, and Self-Care Behavior in Glycemic Control: Results of a Multi-National Online Survey. J. Clinical Medicine, 2019, 8(109), https://doi.org/10.3390/jcm8010109. 
4.	Mihiretu M Kebede, Claudia R Pischke, Popular diabetes apps and the impact of diabetes app use on self-care behaviour: A survey among the digital community of persons with diabetes on Social Media, Frontiers in Endocrinology 2019, 10(135) 10.3389/fendo.2019.00135, https://doi.org/10.3389/fendo.2019.00135.  
5.	Mihiretu Kebede, Hajo Zeeb, Manuela Peters, Thomas H. Heisse,Claudia Pischke, Comparison of Three Meta-analytic Methods Using Data From Digital Interventions on Type 2 Diabetes, In press at Diabetes, Metabolic Syndrome and Obesity: Targets and Therapy, 2018 Dec 19;12:59-73. doi: https://doi.org/10.2147/DMSO.S180106. eCollection 2019.
6.	Mihiretu M. Kebede, Hajo Zeeb, Manuela Peters, Thomas L. Heise, and Claudia R. Pischke. Effectiveness of Digital Interventions for Improving Glycemic Control in Persons with Poorly Controlled Type 2 Diabetes: A Systematic Review, Meta-analysis, and Meta-regression Analysis. Diabetes Technol Therapeutics. 2018 Nov;20(11):767-782. https://doi.org/10.1089/dia.2018.0216. Epub 2018 Sep 26. 
7.	Kebede MM, Liedtke TP, Möllers T, Pischke CR: Characterizing Active Ingredients of eHealth Interventions Targeting Persons With Poorly Controlled Type 2 Diabetes Mellitus Using the Behavior Change Techniques Taxonomy: Scoping Review. Journal of medical Internet research 2017, 19(10):e348-e348, https://www.jmir.org/2017/10/e348/.
8.	Kebede M, Christianson L, Khan Z, Heise TL, Pischke CR: Effectiveness of behavioral change techniques employed in eHealth interventions designed to improve glycemic control in persons with poorly controlled type 2 diabetes: a systematic review and meta-analysis protocol. Systematic reviews 2017, 6(1):211.
9.	Kebede M, Steenbock B, Helmer SM, Sill J, Möllers T, Pischke CR Identifying Evidence-Informed Physical Activity Apps: Content Analysis JMIR Mhealth Uhealth 2018;6(12):e10314 DOI: 10.2196/10314 
10.	Kebede Mihiretu, Steenbock B, Helmer SM, Sill J, Möllers T, Pischke CR, There Are Many Physical Activity Apps But Only Few Are Evidence-Informed:     Results of a Content-Analysis, JMIR mHealth and uHealth. (forthcoming/in press), DOI: 10.2196/10314, URL: https://preprints.jmir.org/preprint/10314.
11.	Adamu Takele Jemere, Yohannes Ezezew Yeneneh, Biniam Tilahun, Fleur Fritz (PhD), Shitaye Alemu, Mihiretu Kebede, Access to mobile phone and willingness to receive mobile phone-based health services among diabetic patients in Northwest Ethiopia, BMJ Open. 2019 Jan 24;9(1):e021766. doi: 10.1136/bmjopen-2018-021766. 
12.	Yeshiwas S, Kiflie M, Zeleke AA, Kebede M. Civil servants' demand for social health insurance in Northwest Ethiopia. Arch Public Health. 2018;76:48. Published 2018 Sep 13. doi:10.1186/s13690-018-0297-x.
13.	Kebede M, Zegeye DT, Zeleke BM: Predicting CD4 count changes among patients on antiretroviral treatment: Application of data mining techniques. Computer methods and programs in biomedicine 2017, 152:149-157.
14.	Dilu E, Gebreslassie M, Kebede M. Human Resource Information System implementation readiness in the Ethiopian health sector: a cross-sectional study. Hum Resour Health. 2017;15(1):85. Published 2017 Dec 20. doi:10.1186/s12960-017-0259-3.
15.	Rahel Abiy,  Kassahun Gashu, Tarekegn Asemaw, Mebratu Mitiku, Berhanu Fekadie, Zeleke Abebaw, Adane Mamuye, Ashenafi Tazebew, Alemayehu Teklu, Fedilu Nurhussien, Mihiretu Kebede, Fleur Fritz,  and Binyam Tilahun  A Comparison of Electronic Medical Record Data to Paper Records in Antiretroviral Therapy Clinic in Ethiopia: What is affecting the Quality of the Data?. Online J Public Health Inform. 2018;10(2):e212. Published 2018 Sep 21. doi:10.5210/ojphi.v10i2.8309.
16.	Astatikie G, Limenih MA, Kebede M: Maternal and fetal outcomes of uterine rupture and factors associated with maternal death secondary to uterine rupture. BMC pregnancy and childbirth 2017, 17(1):117, https://doi.org/10.1186/s12884-017-1302-z.
17.	Beshir  MA,  Woreta  SA,  Kebede  M:  Evidence-based  practice  among  health professionals in hospitals of Northwest Ethiopia: a cross-sectional study. International journal of evidence-based healthcare 2017, 15(4):161-170.
18.	Kebede M, Endris Y, Zegeye DT: Nursing care documentation practice: The unfinished task of nursing care in the University of Gondar Hospital. Informatics for Health and Social Care 2017, 42(3):290-302.
19.	Kebede M, Schmaus-Klughammer AE, Tekle BT. Manuscript Submission Invitations from 'Predatory Journals': What Should Authors Do?. J Korean Med Sci. 2017;32(5):709-712.
20.	Kebede M, Zeleke A, Asemahagn M, Fritz F: Willingness to receive text message medication reminders among patients on antiretroviral treatment in North West Ethiopia: A cross-sectional study. BMC medical informatics and decision making 2015, 15(1):65, https://doi.org/10.1186/s12911-015-0193-z.
21.	Kebede MM, Bazie BB, Abate GB, Zeleke AA: Knowledge of abortion legislation among female preparatory school students in Dabat District, Ethiopia. African Journal of Reproductive Health 2016, 20(4):13-21.
22.	Wassie MA, Zeleke AA, Dachew BA, Kebede M: Evidence-based practice and its associated factors among medical laboratory professionals in West Amhara hospitals, Northwest Ethiopia. International journal of evidence-based healthcare 2017. doi: 10.1097/XEB.0000000000000122, PMID: 28937412.
23.	Tesfaye B, Atique S, Elias N, Dibaba L, Shabbir S-A, Kebede M: Determinants and development of a web-based child mortality prediction model in resource-limited settings: A data mining approach. Computer methods and programs in biomedicine 2017, 140:45-51.
24.	Tesfaye B, Mathewos T, Kebede M: Skilled delivery inequality in Ethiopia: to what extent are the poorest and uneducated mothers benefiting? International journal for equity in health 2017, 16(1):82.
25.	Fritz F, Kebede M, Tilahun B: The need for cost-benefit analyses of eHealth in low and middle-income countries. In: MedInfo: 2015; 2015: 981.
26.	Gashu KD, Meshesha M, Kebede M: HIV counseling and testing uptake among adults in Amhara region; North West Ethiopia. East African Journal of Public Health 2015, 12(1):956-963.
27.	Tilahuna B, Zelekea A, Fritzb F, Kebede M, Andualema M, Assefaa S, Melesea T, Zegeyea D, Gebeyehuc A, Yifru S: Towards problem-based health informatics education and research: ten years of experience and future directions in Ethiopia. 2014.

