---
name: "Aspire Data Solutions"
output_dir: "."
title: "Animating bar graphs"
categories: 
  - Data Science
author: Mihiretu Kebede
url: http://www.mihiretukebede.com/ 
google_analytics: "UA-173027539-1"
date: "2020-07-13"
description: |
  Here we will have a quick look on how to create `Gif` or animated bar plots
collections:
  posts:
      share: [twitter, linkedin, facebook, google-plus, pinterest]
output:
  distill::distill_article:
    self_contained: false
    encoding: UTF-8
---
<head>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4447780400240825" crossorigin="anonymous"></script>
</head>

<link rel="stylesheet" href="styles.css" type="text/css">

Hello, this is my first ever blog post. Detail explanations of this data vizualization and other upcoming blogs are coming soon! Stay tuned. 
  
```{r, echo=TRUE, include=TRUE}
#Set working directory
#setwd("F:/github/githubwebsite")

library(readxl)
mystepcount <- read_excel("F:/github/githubwebsite/mystepcount.xlsx")

str(mystepcount)

library(ggplot2)
library(gganimate)
library(scales)
theme_set(theme_bw())

mystepcount$September <- as.character(mystepcount$September)

```

```{r, layout="l-body-outset", preview=TRUE}

#Plot step counts on the y-axis and days of September on the x-axis
ggplot(mystepcount, aes(x=September,y=Steps)) + 
  geom_bar(fill="darkturquoise", stat="identity", width=1, position=position_dodge()) + 
    geom_hline(yintercept = 10000, col="black", size=1)
```


```{r, echo=TRUE, include=TRUE}
animate(
  ggplot(mystepcount, aes(x=September,y=Steps)) + 
  geom_bar(fill="darkturquoise", stat="identity", width=1, position=position_dodge()) + 
    geom_hline(yintercept = 10000, col="black", size=1) +
  transition_states(September, wrap = FALSE) +
  shadow_mark() +
  enter_grow() +
  enter_fade() + 
  theme(axis.text = element_text(size=16),
        axis.title = element_text(size=16, face="bold")) + 
  xlab("September") +  
  scale_y_discrete(name="Step counts", limits=factor(c(5000,10000, 15000, 20000, 25000, 30000))) +
  theme(axis.line = element_line(colour = "black"),
          panel.border = element_blank()) ,
  
  duration = 5
  )
```  

## Contact 
Please mention [MihiretuKebede1](https://www.https://twitter.com/MihiretuKebede1) if you tweet this post. 